In [5]:
import numpy as np  
import pandas as pd  
from sklearn.linear_model import Lasso  
from sklearn.model_selection import train_test_split  
from sklearn.metrics import mean_squared_error  
import statsmodels.api as sm

In [6]:
np.random.seed(0)  
n_samples = 5000  
X = np.random.rand(n_samples, 5)  # 创建5个特征的自变量  
y = 5 * X[:, 0] + 10 * X[:, 1] + np.random.randn(n_samples)  # 创建因变量，其中只有两个特征与因变量相关

In [7]:
data = pd.DataFrame(X, columns=['Feature1', 'Feature2', 'Feature3', 'Feature4', 'Feature5'])  
data['Target'] = y  
data

      Feature1  Feature2  Feature3  Feature4  Feature5     Target
0     0.548814  0.715189  0.602763  0.544883  0.423655   9.980466
1     0.645894  0.437587  0.891773  0.963663  0.383442   8.637132
2     0.791725  0.528895  0.568045  0.925597  0.071036   9.590819
3     0.087129  0.020218  0.832620  0.778157  0.870012   1.092990
4     0.978618  0.799159  0.461479  0.780529  0.118274  13.176288
...        ...       ...       ...       ...       ...        ...
4995  0.482611  0.738442  0.368384  0.380349  0.704901  10.318834
4996  0.555126  0.159482  0.376645  0.722005  0.889248   2.521278
4997  0.933956  0.821789  0.470160  0.434186  0.510482  10.619461
4998  0.569828  0.268731  0.675069  0.717907  0.256199   6.309839
4999  0.339852  0.612616  0.666182  0.950251  0.193011   8.044170

[5000 rows x 6 columns]